require('./src/complier/complier-pdf-hard')
require('./src/complier/complier-pdf-soft')
require('./src/complier/complier-h5-fd')
require('./src/complier/complier-h5-fm')
require('./src/complier/complier-thumbnail')
require('./src/complier/complier-h5')
